name: "CI"

on:
  push:

jobs:
  build:
    name: "🏗️ LaTeX build"
    runs-on: ubuntu-18.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🏗️ Build LaTeX class"
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: paper.tex
      - name: "📤 Upload paper"
        uses: actions/upload-artifact@v2
        with:
          path: paper/paper.pdf
          name: LaTeX class documentation